@startuml
!include <osa/printer/printer>
skinparam actorStyle awesome
:Lehrkraft: --> (Einloggen)
:Schüler: --> (Emailadresse)
package Entlehnliste {
    (Entlehnliste) .> (<$printer>)
    :Lehrkraft: --> (Entlehnliste)
}
(Emailadresse) .> (Benachrichtigungen)
(Einloggen) --> (Klasse wählen)
(Klasse wählen) --> (Gerät wählen)
(Klasse wählen) .> (Daten der Schüler werden automatisch generiert)
(Emailadresse) ..> (Daten der Schüler werden automatisch generiert)

@enduml